language: php

git:
  depth: 5

matrix:
  include:
    - php: 5.4
      env:
        - LARAVEL_VERSION='4.2.*'
        - PUG_VERSION='^2.7.1'
    - php: 5.5
      env:
        - LARAVEL_VERSION='4.2.*'
        - PUG_VERSION='^2.7.1'
    - php: 5.5
      env:
        - LARAVEL_VERSION='4.2.*'
        - PUG_VERSION='^3.0.0@beta'
    - php: 5.5
      env:
        - LARAVEL_VERSION='5.2.*'
        - PUG_VERSION='^2.7.1'
    - php: 5.5
      env:
        - LARAVEL_VERSION='5.2.*'
        - PUG_VERSION='^3.0.0@beta'
    - php: 5.6
      env:
        - LARAVEL_VERSION='4.2.*'
        - PUG_VERSION='^2.7.1'
    - php: 5.6
      env:
        - LARAVEL_VERSION='4.2.*'
        - PUG_VERSION='^3.0.0@beta'
    - php: 5.6
      env:
        - LARAVEL_VERSION='5.4.*'
        - PUG_VERSION='^2.7.1'
    - php: 5.6
      env:
        - LARAVEL_VERSION='5.4.*'
        - PUG_VERSION='^3.0.0@beta'
    - php: 7.0
      env:
        - LARAVEL_VERSION='4.2.*'
        - PUG_VERSION='^2.7.1'
    - php: 7.0
      env:
        - LARAVEL_VERSION='4.2.*'
        - PUG_VERSION='^3.0.0@beta'
    - php: 7.0
      env:
        - LARAVEL_VERSION='5.4.*'
        - PUG_VERSION='^2.7.1'
    - php: 7.0
      env:
        - LARAVEL_VERSION='5.4.*'
        - PUG_VERSION='^3.0.0@beta'
    - php: 7.0
      env:
        - LARAVEL_VERSION='5.5.*'
        - PUG_VERSION='^2.7.1'
    - php: 7.0
      env:
        - LARAVEL_VERSION='5.5.*'
        - PUG_VERSION='^3.0.0@beta'
    - php: 7.1
      env:
        - LARAVEL_VERSION='4.2.*'
        - PUG_VERSION='^2.7.1'
    - php: 7.1
      env:
        - LARAVEL_VERSION='4.2.*'
        - PUG_VERSION='^3.0.0@beta'
    - php: 7.1
      env:
        - LARAVEL_VERSION='5.4.*'
        - PUG_VERSION='^2.7.1'
    - php: 7.1
      env:
        - LARAVEL_VERSION='5.4.*'
        - PUG_VERSION='^3.0.0@beta'
    - php: 7.1
      env:
        - LARAVEL_VERSION='5.5.*'
        - PUG_VERSION='^2.7.1'
    - php: 7.1
      env:
        - LARAVEL_VERSION='5.5.*'
        - PUG_VERSION='^3.0.0@beta'
    - php: 7.2
      env:
        - LARAVEL_VERSION='4.2.*'
        - PUG_VERSION='^2.7.1'
    - php: 7.2
      env:
        - LARAVEL_VERSION='4.2.*'
        - PUG_VERSION='^3.0.0@beta'
    - php: 7.2
      env:
        - LARAVEL_VERSION='5.4.*'
        - PUG_VERSION='^2.7.1'
    - php: 7.2
      env:
        - LARAVEL_VERSION='5.4.*'
        - PUG_VERSION='^3.0.0@beta'
    - php: 7.2
      env:
        - LARAVEL_VERSION='5.5.*'
        - PUG_VERSION='2.7.1'
    - php: 7.2
      env:
        - LARAVEL_VERSION='5.5.*'
        - PUG_VERSION='^3.0.0@beta'
    - php: hhvm
      env:
        - LARAVEL_VERSION='4.2.*'
        - PUG_VERSION='2.7.1'
      dist: trusty
      sudo: required
    - php: hhvm
      env:
        - LARAVEL_VERSION='4.2.*'
        - PUG_VERSION='^3.0.0@beta'
      dist: trusty
      sudo: required
    - php: hhvm
      env:
        - LARAVEL_VERSION='5.4.*'
        - PUG_VERSION='^2.7.1'
      dist: trusty
      sudo: required
    - php: hhvm
      env:
        - LARAVEL_VERSION='5.4.*'
        - PUG_VERSION='^3.0.0@beta'
      dist: trusty
      sudo: required

install:
  - travis_retry composer self-update
  - if [ "LARAVEL_VERSION" != "" ]; then travis_retry php tests/setLaravelVersion.php $LARAVEL_VERSION; fi;
  - travis_retry composer update --no-interaction --prefer-stable

script:
  - vendor/bin/phpunit --verbose --coverage-text --coverage-clover=coverage.xml

after_script:
  - vendor/bin/test-reporter --coverage-report coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)

addons:
  code_climate:
    repo_token: b9dac85e7024fb18994b92d2d92f8026cd9be15ef620b9a9f4095e6754a1b3de
