language: php

git:
  depth: 5

matrix:
  include:
    - php: 5.4
      env:
        - LARAVEL_VERSION='4.2.*'
        - PUG_VERSION='^2.7'
    - php: 5.5
      env:
        - LARAVEL_VERSION='4.2.*'
        - PUG_VERSION='^2.7'
    - php: 5.5
      env:
        - LARAVEL_VERSION='4.2.*'
        - PUG_VERSION='^3.0'
    - php: 5.5
      env:
        - LARAVEL_VERSION='5.2.*'
        - PUG_VERSION='^2.7'
    - php: 5.5
      env:
        - LARAVEL_VERSION='5.2.*'
        - PUG_VERSION='^3.0'
    - php: 5.6
      env:
        - LARAVEL_VERSION='4.2.*'
        - PUG_VERSION='^2.7'
    - php: 5.6
      env:
        - LARAVEL_VERSION='4.2.*'
        - PUG_VERSION='^3.0'
    - php: 5.6
      env:
        - LARAVEL_VERSION='5.4.*'
        - PUG_VERSION='^2.7'
    - php: 5.6
      env:
        - LARAVEL_VERSION='5.4.*'
        - PUG_VERSION='^3.0'
    - php: 7.0
      env:
        - LARAVEL_VERSION='4.2.*'
        - PUG_VERSION='^2.7'
    - php: 7.0
      env:
        - LARAVEL_VERSION='4.2.*'
        - PUG_VERSION='^3.0'
    - php: 7.0
      env:
        - LARAVEL_VERSION='5.4.*'
        - PUG_VERSION='^2.7'
    - php: 7.0
      env:
        - LARAVEL_VERSION='5.4.*'
        - PUG_VERSION='^3.0'
    - php: 7.0
      env:
        - LARAVEL_VERSION='5.5.*'
        - PUG_VERSION='^2.7'
    - php: 7.0
      env:
        - LARAVEL_VERSION='5.5.*'
        - PUG_VERSION='^3.0'
    - php: 7.1
      env:
        - LARAVEL_VERSION='4.2.*'
        - PUG_VERSION='^2.7'
    - php: 7.1
      env:
        - LARAVEL_VERSION='4.2.*'
        - PUG_VERSION='^3.0'
    - php: 7.1
      env:
        - LARAVEL_VERSION='5.4.*'
        - PUG_VERSION='^2.7'
    - php: 7.1
      env:
        - LARAVEL_VERSION='5.4.*'
        - PUG_VERSION='^3.0'
    - php: 7.1
      env:
        - LARAVEL_VERSION='5.5.*'
        - PUG_VERSION='^2.7'
    - php: 7.1
      env:
        - LARAVEL_VERSION='5.5.*'
        - PUG_VERSION='^3.0'
    - php: 7.2
      env:
        - LARAVEL_VERSION='4.2.*'
        - PUG_VERSION='^2.7'
    - php: 7.2
      env:
        - LARAVEL_VERSION='4.2.*'
        - PUG_VERSION='^3.0'
    - php: 7.2
      env:
        - LARAVEL_VERSION='5.4.*'
        - PUG_VERSION='^2.7'
    - php: 7.2
      env:
        - LARAVEL_VERSION='5.4.*'
        - PUG_VERSION='^3.0'
    - php: 7.2
      env:
        - LARAVEL_VERSION='5.5.*'
        - PUG_VERSION='^2.7'
    - php: 7.2
      env:
        - LARAVEL_VERSION='5.5.*'
        - PUG_VERSION='^3.0'
    - php: 7.3
      env:
      - LARAVEL_VERSION='4.2.*'
      - PUG_VERSION='^2.7'
    - php: 7.3
      env:
      - LARAVEL_VERSION='4.2.*'
      - PUG_VERSION='^3.0'
    - php: 7.3
      env:
      - LARAVEL_VERSION='5.4.*'
      - PUG_VERSION='^2.7'
    - php: 7.3
      env:
      - LARAVEL_VERSION='5.4.*'
      - PUG_VERSION='^3.0'
    - php: 7.3
      env:
      - LARAVEL_VERSION='5.5.*'
      - PUG_VERSION='^2.7'
    - php: 7.3
      env:
      - LARAVEL_VERSION='5.5.*'
      - PUG_VERSION='^3.0'
    - php: 7.3
      env:
      - LARAVEL_VERSION='5.6.*'
      - PUG_VERSION='^2.7'
    - php: 7.3
      env:
      - LARAVEL_VERSION='5.6.*'
      - PUG_VERSION='^3.0'
    - php: 7.3
      env:
      - LARAVEL_VERSION='5.7.*'
      - PUG_VERSION='^2.7'
    - php: 7.3
      env:
      - LARAVEL_VERSION='5.7.*'
      - PUG_VERSION='^3.0'
    - php: 7.3
      env:
      - LARAVEL_VERSION='5.8.*'
      - PUG_VERSION='^2.7'
    - php: 7.3
      env:
      - LARAVEL_VERSION='5.8.*'
      - PUG_VERSION='^3.0'
    - php: hhvm
      env:
        - LARAVEL_VERSION='4.2.*'
        - PUG_VERSION='^2.7'
      dist: trusty
      sudo: required
    - php: hhvm
      env:
        - LARAVEL_VERSION='4.2.*'
        - PUG_VERSION='^3.0'
      dist: trusty
      sudo: required
    - php: hhvm
      env:
        - LARAVEL_VERSION='5.4.*'
        - PUG_VERSION='^2.7'
      dist: trusty
      sudo: required
    - php: hhvm
      env:
        - LARAVEL_VERSION='5.4.*'
        - PUG_VERSION='^3.0'
      dist: trusty
      sudo: required

install:
  - travis_retry composer self-update
  - travis_retry php tests/setDependenciesVersions.php $LARAVEL_VERSION $PUG_VERSION
  - travis_wait 30 travis_retry composer update --no-interaction

script:
  - vendor/bin/phpunit --verbose --coverage-text --coverage-clover=coverage.xml

after_script:
  - if [[ $LARAVEL_VERSION == "5.4.*" && $PUG_VERSION == "^3.0" && ${TRAVIS_PHP_VERSION:0:3} == "5.6" ]]; then vendor/bin/test-reporter --coverage-report coverage.xml; fi;

after_success:
  - if [[ $LARAVEL_VERSION == "5.4.*" && $PUG_VERSION == "^3.0" && ${TRAVIS_PHP_VERSION:0:3} == "5.6" ]]; then bash <(curl -s https://codecov.io/bash); fi;

addons:
  code_climate:
    repo_token: b9dac85e7024fb18994b92d2d92f8026cd9be15ef620b9a9f4095e6754a1b3de
