language: php

git:
  depth: 5

env:
  global:
    - COMPOSER_FLAGS=''
    - CC_TEST_REPORTER_ID=b9dac85e7024fb18994b92d2d92f8026cd9be15ef620b9a9f4095e6754a1b3de

cache:
  apt: true
  directories:
    - $HOME/.composer/cache

matrix:
  include:
    - php: 7.2
      env: COMPOSER_FLAGS='--prefer-lowest'
    - php: 7.2
    - php: 7.3
    - php: 7.4
      env: COVERAGE=true
    - php: nightly
      env: COMPOSER_FLAGS='--ignore-platform-reqs'

install:
  - if [[ "$COVERAGE" != "true" ]]; then phpenv config-rm xdebug.ini || echo 'XDebug already disabled'; fi;
  - travis_retry composer self-update
  - COMPOSER_MEMORY_LIMIT=-1 travis_wait 30 travis_retry composer update --no-interaction ${COMPOSER_FLAGS}

before_script:
  - |
    if [ "$COVERAGE" = "true" ]; then
      curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
      chmod +x ./cc-test-reporter
      ./cc-test-reporter before-build
    fi

script:
  - if [[ "$COVERAGE" = "true" ]]; then vendor/bin/phpunit --verbose --coverage-text --coverage-clover=coverage.xml; fi;
  - if [[ "$COVERAGE" != "true" ]]; then vendor/bin/phpunit --verbose --no-coverage; fi;

after_script:
  - if [[ "$COVERAGE" = "true" ]]; then vendor/bin/test-reporter --coverage-report coverage.xml; fi;

after_success:
  - if [[ "$COVERAGE" = "true" ]]; then bash <(curl -s https://codecov.io/bash); fi;
